repos:
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.27.1
  hooks:
  - id: markdownlint
- repo: https://github.com/trussworks/pre-commit-hooks
  rev: v1.0.0
  hooks:
    - id: mdspell
    - id: spelling-sort
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
      language_version: python3
- repo: local
  hooks:
    - id: custom-checks
      additional_dependencies: [pypdf==4.0.0]
      name: custom-checks
      entry: python checks.py
      language: python
      pass_filenames: false