name: Fix links

on:
  workflow_dispatch:
  schedule:
    - cron: '10 2 * * 3'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Setup git
        run: |
          git config --global user.name "Links Fixer"
          git config --global user.email "actions@users.noreply.github.com"
          git config --global url.https://github.com/.insteadOf git://github.com/
      - name: Set branch name
        run: |
          echo "BRANCH_NAME=link-fix-$(date '+%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV
          echo ${{ env.BRANCH_NAME }}
      - name: Switch to branch ${{ env.BRANCH_NAME }}
        run: |
          git checkout -b ${{ env.BRANCH_NAME }}
      - name: Fix links
        run: |
          python src/link_fix.py
        continue-on-error: false

      # Check if broken_links.md exists before creating the issue
      - name: Check for broken links file
        id: broken_links
        run: |
          if [ -f ./broken_links.md ]; then
            echo "Broken links file found"
            echo "found=true" >> $GITHUB_ENV
          else
            echo "Broken links file not found"
            echo "found=false" >> $GITHUB_ENV
          fi
        continue-on-error: false

      # Create issue if the broken_links.md file exists
      - name: Create Issue From File
        if: env.found == 'true'
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Broken internal links report
          content-filepath: ./broken_links.md
          labels: report, automated issue

      - name: Commit changes if any
        id: commit
        run: |
          rm -f broken_links.md
          git commit -a -m 'Fix links'
        continue-on-error: false

      - name: Push branch if there are changes
        if: ${{ steps.commit.outcome == 'success' }}
        run: |
          git push --set-upstream origin ${{ env.BRANCH_NAME }}

      - name: Delete branch if no changes
        if: ${{ steps.commit.outcome != 'success' }}
        run: |
          git checkout main && git branch -D ${{ env.BRANCH_NAME }}
      - name: Create pull request
        if: ${{ steps.commit.outcome == 'success' }}
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "${{ env.BRANCH_NAME }}"
          destination_branch: "main"
          pr_title: "Fix links"
          pr_body: |
            *Fixed links*
