name: Markdown Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  markdownlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run markdownlint
        uses: davidanson/markdownlint-cli2-action@v3
        with:
          fix: true
          files: '**/*.md'
